version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo_db
    networks:
      - red

  mongo_db:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - red

networks:
  red:

volumes:
  mongo_data:
