services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql_db
    volumes:
      - .:/app
    networks:
      - red

  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: usuariosdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql          # Volumen persistente
      - ./init:/docker-entrypoint-initdb.d  # Script de inicialización
    networks:
      - red

networks:
  red:

volumes:
  db_data:
