version: '3.8'
services:
  app:
    build: .
    container_name: api_trabajadores_app
    restart: unless-stopped
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/trabajadores
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - appnet

  mongo:
    image: mongo:latest
    container_name: api_trabajadores_mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - appnet

volumes:
  mongo_data:

networks:
  appnet:
    driver: bridge
